language: php

php:
  - 5.5

install:
  - composer self-update
  - composer update

script:
  - vendor/bin/phpunit --verbose --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
